<a href="https://colab.research.google.com/github/cjfghk5697/Practice_Pytorch/blob/main/Practice_pytorch2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import os
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets, transforms

In [ ]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print('Using {} device'.format(device))

Using cpu device


In [ ]:
class NeuralNetwork(nn.Module):
    def __init__(self):
        super(NeuralNetwork, self).__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28*28, 512),
            nn.ReLU(),
            nn.Linear(512, 512),
            nn.ReLU(),
            nn.Linear(512, 10),
            nn.ReLU()
        )

    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits

In [ ]:
model = NeuralNetwork().to(device)
print(model)

NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
    (5): ReLU()
  )
)


In [ ]:
X = torch.rand(1, 28, 28, device=device) #input 값
logits = model(X)
pred_probab = nn.Softmax(dim=1)(logits) #predict
y_pred = pred_probab.argmax(1) # 5가 나옴 왜냐하면 인덱스 위치임
print(f"Predicted class: {y_pred}")
print(y_pred)#합이 1(소프트맥스 거침), 확률 인덱스 5가 가장 높음
print(logits)# =소프트맥스 안거쳐서 

Predicted class: tensor([5])
tensor([5])
tensor([[0.0085, 0.0000, 0.0377, 0.0000, 0.0000, 0.0785, 0.0083, 0.0157, 0.0000,
         0.0000]], grad_fn=<ReluBackward0>)


In [ ]:
input_image = torch.rand(3,28,28)
print(input_image.size())

torch.Size([3, 28, 28])


In [ ]:
flatten = nn.Flatten() #가로 세로 차원인걸 납작하게 만드는 거임. 위에 torch.size 차원 하나가 없어짐.
flat_image = flatten(input_image)
print(flat_image.size())

torch.Size([3, 784])


In [ ]:
layer1 = nn.Linear(in_features=28*28, out_features=20) #linear함수 input은 28*28인거고 출력은 20이라는 의미
hidden1 = layer1(flat_image)
print(hidden1.size())

torch.Size([3, 20])


In [ ]:
print(f"Before ReLU: {hidden1}\n\n")
hidden1 = nn.ReLU()(hidden1)
print(f"After ReLU: {hidden1}") #ReLu 통과하니 음수가 다 사라짐. 

Before ReLU: tensor([[-0.3879, -0.0240,  0.1556,  0.4399, -0.1004,  0.1211, -0.6378,  0.2039,
         -0.0570, -0.0019, -0.2433, -0.1175,  0.7778,  0.0090,  0.3098, -0.0203,
         -0.1514,  0.0407,  0.6663, -0.4235],
        [-0.2811, -0.2628,  0.0299,  0.1144, -0.1560, -0.0874, -0.2853,  0.3454,
          0.2419, -0.1653, -0.2607, -0.6672,  0.4166,  0.0070,  0.0565,  0.1906,
         -0.3233, -0.2292,  0.6195, -0.2466],
        [-0.2199,  0.0690, -0.1446,  0.9191, -0.0802,  0.2488, -0.2844,  0.2891,
          0.1376, -0.1360, -0.2836, -0.2114,  0.3778,  0.4768,  0.4910, -0.0340,
         -0.3694, -0.0073,  0.3877, -0.1632]], grad_fn=<AddmmBackward>)


After ReLU: tensor([[0.0000, 0.0000, 0.1556, 0.4399, 0.0000, 0.1211, 0.0000, 0.2039, 0.0000,
         0.0000, 0.0000, 0.0000, 0.7778, 0.0090, 0.3098, 0.0000, 0.0000, 0.0407,
         0.6663, 0.0000],
        [0.0000, 0.0000, 0.0299, 0.1144, 0.0000, 0.0000, 0.0000, 0.3454, 0.2419,
         0.0000, 0.0000, 0.0000, 0.4166, 0.0070, 0.056

In [ ]:
seq_modules = nn.Sequential(
    flatten,
    layer1, # 총 4개의 레이어가 실행됨 flatte-> layer1..
    nn.ReLU(),
    nn.Linear(20, 10)
)
input_image = torch.rand(3,28,28)
logits = seq_modules(input_image)
print(logits.shape) #데이터 3개, 각각 10개의 값을 가지고 있다.

torch.Size([3, 10])


In [ ]:
softmax = nn.Softmax(dim=1)
pred_probab = softmax(logits)
print(logits)
print(pred_probab)
print(pred_probab.shape)

tensor([[ 0.1985, -0.0796, -0.3076, -0.1423,  0.1808,  0.0322, -0.2737, -0.2152,
          0.1923, -0.0989],
        [ 0.0941, -0.0910, -0.3788, -0.1590,  0.2748,  0.0651, -0.2367, -0.2237,
          0.2224,  0.0041],
        [ 0.2297,  0.0825, -0.3219, -0.0544,  0.0638,  0.1046, -0.2203, -0.1299,
          0.2527,  0.0393]], grad_fn=<AddmmBackward>)
tensor([[0.1262, 0.0956, 0.0761, 0.0898, 0.1240, 0.1069, 0.0787, 0.0835, 0.1255,
         0.0938],
        [0.1124, 0.0934, 0.0700, 0.0873, 0.1347, 0.1092, 0.0807, 0.0818, 0.1278,
         0.1027],
        [0.1233, 0.1065, 0.0711, 0.0928, 0.1045, 0.1089, 0.0787, 0.0861, 0.1262,
         0.1020]], grad_fn=<SoftmaxBackward>)
torch.Size([3, 10])


In [20]:
print("Model structure: ", model, "\n\n")

for name, param in model.named_parameters():
    print(f"Layer: {name} | Size: {param.size()} | Values : {param[:2]} \n") #학습시켜나갈 파라미터 Relu는 파라미터 없음

Model structure:  NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
    (5): ReLU()
  )
) 


Layer: linear_relu_stack.0.weight | Size: torch.Size([512, 784]) | Values : tensor([[-0.0047,  0.0270, -0.0304,  ...,  0.0190, -0.0282, -0.0307],
        [-0.0290, -0.0048, -0.0251,  ...,  0.0287,  0.0268,  0.0221]],
       grad_fn=<SliceBackward>) 

Layer: linear_relu_stack.0.bias | Size: torch.Size([512]) | Values : tensor([-0.0302, -0.0105], grad_fn=<SliceBackward>) 

Layer: linear_relu_stack.2.weight | Size: torch.Size([512, 512]) | Values : tensor([[-0.0371, -0.0160, -0.0410,  ..., -0.0008,  0.0409,  0.0407],
        [ 0.0005,  0.0388, -0.0280,  ..., -0.0384, -0.0200, -0.0148]],
       grad_fn=<SliceBackward>) 

Layer: linear_relu_